### ISSUE TITLE
No success with local install

### ISSUE THREAD

**Issue by heinzr** [MarcKletz/OMR-MeasureRecognition#3]
I tried to install locally with the intent to just run inference.
Things seem to progress nicely (apart from having to install a lot of stuff), but run Streamlit failed (see attached log).
I had pytorch 1.7 already installed.
[run_streamlit.log](https://github.com/MarcKletz/OMR-MeasureRecognition/files/6031862/run_streamlit.log)

**Comment by MarcKletz** [comment]
This error comes from having an older version of protobuf installed, and can be fixed by the following: 
pip install --upgrade protobuf.

Other than that, I created a new script /inference_with_user_data.py which should demonstrate how to use this repos' functionality to predict on user data and generate json files from the predictions.

Let me know if upgrading protobuf works though, would be interested in that!
